site_name: Documentation
site_description: Documentation for My Project
site_author: Your Name

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: images/fb-logo.png
  favicon: images/fb-logo.png
  font:
    text: Open Sans
    code: Fira Code
  palette:
    scheme: slate # Dark mode only, no toggle
    primary: black # overridden by CSS
    accent: black # overridden by CSS
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.collapse
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share

nav:
  - Documentation:
      - Overview: index.md
      - Features: features.md
      - Team: team.md
      - User Stories: user_stories.md
      - Tech stack: tech-stack.md
      - Third Party Code Documentation: Third-Party.md
      - Setup and Installation: setup.md
      - Testing: Testing.md
      - User Feedback: User Feedback.md
      - Database Schema: Database.md
      - UML Diagrams: UML.md
  - Sprints:
      - Sprint 1: Sprint1.md
      - Sprint 2: Sprint2.md
  - API Documentation:
      - Overview: API-Overview.md
      - Getting Started: API-Start.md
      - API Endpoints: API-Endpoints.md
