site_name: FootBook Documentation
site_description: Documentation for My Project
site_author: Your Name

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  font:
    text: Open Sans
    code: Fira Code
  palette:
    scheme: slate # Dark mode only, no toggle
    primary: black # overridden by CSS
    accent: black # overridden by CSS
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.collapse
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share

nav:
  - Documentation:
      - Overview: index.md
      - Features: features.md
      - Team: team.md
      - Tech stack: tech-stack.md
      - Setup and Installation: setup.md
  - Sprints:
      - Sprint 1: Sprint1.md
  - API Services Reference:
      - Coming Soon: comingsoon.md
