site_name: SDP Project Documentation
site_description: Documentation for My Project
site_author: Your Name

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  font:
    text: Open Sans
    code: Fira Code
  palette:
    - scheme: default
      primary: black
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.collapse # allows collapsing
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share

nav:
  - Documentation:
      - Overview: index.md
      - Features: features.md
      - Team: team.md
      - Tech stack: tech-stack.md
      - Setup and Installation: setup.md
  - Sprints:
      - Sprint 1: Sprint1.md
  - API Services Reference:
      - Coming Soon: comingsoon.md
